package com.opw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class listOfServices implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Boolean internationalDialing;
	private Boolean roaming;

	public listOfServices() {
	}

	public java.lang.Boolean getInternationalDialing() {
		return this.internationalDialing;
	}

	public void setInternationalDialing(java.lang.Boolean internationalDialing) {
		this.internationalDialing = internationalDialing;
	}

	public java.lang.Boolean getRoaming() {
		return this.roaming;
	}

	public void setRoaming(java.lang.Boolean roaming) {
		this.roaming = roaming;
	}

	public listOfServices(java.lang.Boolean internationalDialing,
			java.lang.Boolean roaming) {
		this.internationalDialing = internationalDialing;
		this.roaming = roaming;
	}

}