package com.opw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class listOfServices implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String internationalDialing;
	private java.lang.String roaming;

	public listOfServices() {
	}

	public java.lang.String getInternationalDialing() {
		return this.internationalDialing;
	}

	public void setInternationalDialing(java.lang.String internationalDialing) {
		this.internationalDialing = internationalDialing;
	}

	public java.lang.String getRoaming() {
		return this.roaming;
	}

	public void setRoaming(java.lang.String roaming) {
		this.roaming = roaming;
	}

	public listOfServices(java.lang.String internationalDialing,
			java.lang.String roaming) {
		this.internationalDialing = internationalDialing;
		this.roaming = roaming;
	}

}