package com.opw;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class listOfServices implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public listOfServices() {
    }




}